name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: leanprover/lean-action@v1

  docs:
    if: github.event_name != 'pull_request'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
      - uses: leanprover/lean-action@v1
      - name: Build API documentation
        run: |
          cd docbuild
          lake update doc-gen4
          lake build Syncordian:docs
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docbuild/.lake/build/doc
      - id: deployment
        uses: actions/deploy-pages@v4
